const fs = require('fs');
const path = 'src/components/hero/HeroScene.tsx';

const lines = [
"import { useEffect, useRef } from 'react'",
"",
"/* Cherry Blossom Hero — full-screen 2D canvas */",
"interface Branch { x1: number; y1: number; x2: number; y2: number; width: number; depth: number }",
"interface Blossom { x: number; y: number; size: number; opacity: number; phase: number; petalCount: number }",
"interface FallingPetal { x: number; y: number; size: number; rot: number; vx: number; vy: number; rotSpeed: number; wobblePhase: number; wobbleAmp: number; wobbleFreq: number; opacity: number; fadeTimer: number; maxLife: number; color: number[] }",
"interface Star { x: number; y: number; size: number; brightness: number; twinkleSpeed: number; twinkleOffset: number }",
"",
"const PETAL_COLORS = [[249,168,212],[251,207,232],[253,164,175],[252,231,243],[244,114,182],[251,191,236],[255,228,230],[248,180,210]]",
"",
"function seededRandom(seed: number) {",
"  let s = seed",
"  return () => { s = (s * 16807 + 0) % 2147483647; return (s - 1) / 2147483646 }",
"}",
"",
"export default function HeroScene() {",
"  const canvasRef = useRef<HTMLCanvasElement>(null)",
"  useEffect(() => {",
"    const canvas = canvasRef.current",
"    if (!canvas) return",
"    const ctx = canvas.getContext('2d')",
"    if (!ctx) return",
"    let animId = 0, w = 0, h = 0, time = 0",
"    let branches: Branch[] = [], blossoms: Blossom[] = [], fallingPetals: FallingPetal[] = [], stars: Star[] = []",
"",
"    const resize = () => {",
"      const dpr = window.devicePixelRatio || 1",
"      w = window.innerWidth; h = window.innerHeight",
"      canvas.width = w * dpr; canvas.height = h * dpr",
"      canvas.style.width = w + 'px'; canvas.style.height = h + 'px'",
"      ctx.setTransform(dpr, 0, 0, dpr, 0, 0); generateTree()",
"    }",
"",
"    const generateTree = () => {",
"      branches = []; blossoms = []; stars = []",
"      const rand = seededRandom(77)",
"      const baseX = w * 0.48, baseY = h * 1.05, trunkTop = h * 0.25",
"      for (let i = 0; i < 10; i++) {",
"        const t1 = i / 10, t2 = (i + 1) / 10",
"        const c1 = Math.sin(t1 * Math.PI * 0.7) * w * 0.04, c2 = Math.sin(t2 * Math.PI * 0.7) * w * 0.04",
"        branches.push({ x1: baseX + c1 + (rand() - 0.5) * 3, y1: baseY + (trunkTop - baseY) * t1, x2: baseX + c2 + (rand() - 0.5) * 3, y2: baseY + (trunkTop - baseY) * t2, width: Math.max(4, 18 - i * 1.5), depth: 0 })",
"      }",
"      const cfgs = [{ a: -0.6, l: 0.35, s: 0.15 }, { a: -1.2, l: 0.30, s: 0.12 }, { a: -1.8, l: 0.25, s: 0.10 }, { a: -2.4, l: 0.28, s: 0.13 }, { a: -0.3, l: 0.32, s: 0.14 }]",
"      cfgs.forEach((cfg, bi) => {",
"        const parent = branches[Math.min(Math.floor((0.3 + bi / 5 * 0.5) * (branches.length - 1)), branches.length - 1)]",
"        const ma = cfg.a + (rand() - 0.5) * 0.3, ml = w * cfg.l",
"        let px = parent.x2, py = parent.y2",
"        const segs = 4 + Math.floor(rand() * 2)",
"        for (let j = 0; j < segs; j++) {",
"          const ang = ma + (rand() - 0.5) * cfg.s, sl = ml / segs",
"          const nx = px + Math.cos(ang) * sl + (rand() - 0.5) * 5, ny = py + Math.sin(ang) * sl + (rand() - 0.5) * 5",
"          branches.push({ x1: px, y1: py, x2: nx, y2: ny, width: Math.max(1, 8 - j * 1.5 - bi * 0.5), depth: 1 })",
"          if (j > 0 && rand() > 0.3) {",
"            const sa = ang + (rand() > 0.5 ? 1 : -1) * (0.4 + rand() * 0.6), sl2 = sl * (0.5 + rand() * 0.5)",
"            const sx = px + Math.cos(sa) * sl2, sy = py + Math.sin(sa) * sl2",
"            branches.push({ x1: px, y1: py, x2: sx, y2: sy, width: Math.max(0.5, 4 - j), depth: 2 })",
"            for (let k = 0; k < 2 + Math.floor(rand() * 4); k++) blossoms.push({ x: sx + (rand() - 0.5) * 25, y: sy + (rand() - 0.5) * 20, size: 5 + rand() * 7, opacity: 0.5 + rand() * 0.5, phase: rand() * Math.PI * 2, petalCount: rand() > 0.3 ? 5 : 6 })",
"            if (rand() > 0.4) {",
"              const ta = sa + (rand() - 0.5) * 0.8, tl = sl2 * 0.6",
"              const tx = sx + Math.cos(ta) * tl, ty = sy + Math.sin(ta) * tl",
"              branches.push({ x1: sx, y1: sy, x2: tx, y2: ty, width: Math.max(0.3, 2 - j * 0.3), depth: 3 })",
"              for (let k = 0; k < 1 + Math.floor(rand() * 3); k++) blossoms.push({ x: tx + (rand() - 0.5) * 18, y: ty + (rand() - 0.5) * 14, size: 4 + rand() * 5, opacity: 0.4 + rand() * 0.5, phase: rand() * Math.PI * 2, petalCount: 5 })",
"            }",
"          }",
"          px = nx; py = ny",
"        }",
"        for (let k = 0; k < 3 + Math.floor(rand() * 5); k++) blossoms.push({ x: px + (rand() - 0.5) * 30, y: py + (rand() - 0.5) * 25, size: 5 + rand() * 8, opacity: 0.5 + rand() * 0.5, phase: rand() * Math.PI * 2, petalCount: rand() > 0.3 ? 5 : 6 })",
"      })",
"      for (let i = 0; i < 30; i++) { const a = rand() * Math.PI * 2, d = rand() * w * 0.2; blossoms.push({ x: baseX + w * 0.04 + Math.cos(a) * d, y: h * 0.2 + Math.sin(a) * d * 0.6, size: 4 + rand() * 6, opacity: 0.3 + rand() * 0.4, phase: rand() * Math.PI * 2, petalCount: 5 }) }",
"      for (let i = 0; i < 120; i++) stars.push({ x: rand() * w, y: rand() * h * 0.7, size: 0.3 + rand() * 1.8, brightness: 0.2 + rand() * 0.6, twinkleSpeed: 0.3 + rand() * 2, twinkleOffset: rand() * Math.PI * 2 })",
"    }",
"",
"    const spawnPetal = () => {",
"      if (!blossoms.length) return",
"      const s = blossoms[Math.floor(Math.random() * blossoms.length)], c = PETAL_COLORS[Math.floor(Math.random() * PETAL_COLORS.length)]",
"      fallingPetals.push({ x: s.x + (Math.random() - 0.5) * 12, y: s.y + (Math.random() - 0.5) * 10, size: 3 + Math.random() * 5, rot: Math.random() * Math.PI * 2, vx: (Math.random() - 0.5) * 0.3, vy: 0.15 + Math.random() * 0.35, rotSpeed: (Math.random() - 0.5) * 0.02, wobblePhase: Math.random() * Math.PI * 2, wobbleAmp: 0.3 + Math.random() * 0.7, wobbleFreq: 0.008 + Math.random() * 0.012, opacity: 0, fadeTimer: 0, maxLife: 300 + Math.random() * 250, color: c })",
"    }",
"",
"    const drawSky = () => {",
"      const g = ctx.createLinearGradient(0, 0, 0, h)",
"      g.addColorStop(0, '#070d1f'); g.addColorStop(0.25, '#0c1633'); g.addColorStop(0.5, '#111f45'); g.addColorStop(0.75, '#182d58'); g.addColorStop(1, '#1e3a6a')",
"      ctx.fillStyle = g; ctx.fillRect(0, 0, w, h)",
"      const mx = w * 0.8, my = h * 0.15",
"      const mg = ctx.createRadialGradient(mx, my, 0, mx, my, w * 0.25)",
"      mg.addColorStop(0, 'rgba(200,220,255,0.08)'); mg.addColorStop(0.3, 'rgba(147,197,253,0.04)'); mg.addColorStop(1, 'rgba(0,0,0,0)')",
"      ctx.fillStyle = mg; ctx.fillRect(0, 0, w, h)",
"      ctx.fillStyle = 'rgba(220,230,255,0.12)'; ctx.beginPath(); ctx.arc(mx, my, 25, 0, Math.PI * 2); ctx.fill()",
"      ctx.fillStyle = 'rgba(230,240,255,0.06)'; ctx.beginPath(); ctx.arc(mx, my, 35, 0, Math.PI * 2); ctx.fill()",
"      stars.forEach(s => { const t = 0.5 + 0.5 * Math.sin(time * 0.02 * s.twinkleSpeed + s.twinkleOffset); ctx.fillStyle = 'rgba(200,220,255,' + (s.brightness * t) + ')'; ctx.beginPath(); ctx.arc(s.x, s.y, s.size, 0, Math.PI * 2); ctx.fill() })",
"      ctx.fillStyle = '#0a1225'; ctx.beginPath(); ctx.moveTo(0, h * 0.85)",
"      for (let x = 0; x <= w; x += 3) ctx.lineTo(x, h * 0.85 + Math.sin(x * 0.003) * h * 0.03 + Math.sin(x * 0.007) * h * 0.015)",
"      ctx.lineTo(w, h); ctx.lineTo(0, h); ctx.closePath(); ctx.fill()",
"    }",
"",
"    const drawBranch = (b: Branch, sway: number) => {",
"      const ds = sway * (1 - b.depth * 0.25), x1 = b.x1 + ds, x2 = b.x2 + ds * 0.7",
"      const r = 55 + b.depth * 12 + Math.floor(Math.sin(time * 0.005 + b.depth) * 3)",
"      ctx.strokeStyle = 'rgb(' + r + ',' + (35 + b.depth * 8) + ',' + (22 + b.depth * 5) + ')'",
"      ctx.lineWidth = Math.max(0.5, b.width); ctx.lineCap = 'round'",
"      const midx = (x1 + b.x2) / 2 + Math.sin(b.depth * 2.5) * 3, midy = (b.y1 + b.y2) / 2 + Math.cos(b.depth * 1.8) * 3",
"      ctx.beginPath(); ctx.moveTo(x1, b.y1); ctx.quadraticCurveTo(midx, midy, x2, b.y2); ctx.stroke()",
"      if (b.depth === 0 && b.width > 8) { ctx.strokeStyle = 'rgba(40,25,15,0.3)'; ctx.lineWidth = 0.5; for (let i = 0; i < 3; 
